### ISSUE TITLE
No termina de funcionar

### ISSUE THREAD

**Issue by vandark25** [elguitarraverde/LogsToFile#1]
Con el plugin activado se siguen viendo los errores en el visor de LOG
![imagen](https://github.com/elguitarraverde/LogsToFile/assets/40995825/412a61c4-16d9-42f4-815b-d63a060e88bc)

**Comment by elguitarraverde** [comment]
@vandark25 ahora mismo solo pasa al archivo los errores del canal "master". incluire tambien los errores de "database"
dime todos los errores que quieres quitar aunque ya creo que incluyendo los de database ya quedaria completo

**Comment by vandark25** [comment]
Con quitar el canal error vale

**Comment by elguitarraverde** [comment]
se modifica el filtro para que se guarden en archivo todos los errores del tipo "error" y "critical" independientemente del "channel".
