### ISSUE TITLE
ver logs en tiempo real

### ISSUE THREAD

**Issue by vandark25** [elguitarraverde/LogsToFile#2]
Estaria genial que se pudiese leer el log mientras se va completando como un .log de toda la vida usando tail.
El problema esta en que cuando se esta generando algun error y quieres leerlo, lo descgargas pero como nunca cierra la llave del json siempre te da error y no salen los datos estructurados...
Se te ocurre algo?

**Comment by elguitarraverde** [comment]
@vandark25 ok, ya lo he puesto para que se vea bonito. no sé si es eso lo que necesitas.

![Animation](https://github.com/elguitarraverde/LogsToFile/assets/2836337/9362c095-fe0a-4aca-9899-bbb08055d262)

**Comment by vandark25** [comment]
Sii ahora siii
